### ISSUE TITLE
Login Page - CSS and JS are not loading

### ISSUE THREAD

**Issue by nkuba** [twostairs/paperwork#210]
On Demo instance styles are not being loaded.

Following errors noted in FireBug on the Login Page:
"NetworkError: 404 Not Found - http://demo.paperwork.rocks/css/themes/paperwork-v1.min.css"
paperwo...min.css
"NetworkError: 404 Not Found - http://demo.paperwork.rocks/js/libraries.min.js"
libraries.min.js
"NetworkError: 404 Not Found - http://demo.paperwork.rocks/js/jquery.min.js"
jquery.min.js
"NetworkError: 404 Not Found - http://demo.paperwork.rocks/js/libraries.min.js"
libraries.min.js

Screenshot:
![screen](https://cloud.githubusercontent.com/assets/10741774/6056938/22e9642a-ad18-11e4-836a-bfaeea201269.png)

Browsers:
Firefox 35.0.1
Chrome 40.0.2214.93 m

**Comment by stephen-hill** [comment]
Ditto

![image](https://cloud.githubusercontent.com/assets/205619/6059464/b5eb2acc-ad29-11e4-827d-b85911736661.png)

**Comment by devilx** [comment]
Fixed for now. Thanks!

**Comment by rpietzsch** [comment]
What commit/branch to pick up the fix? I did ``fig up`` on master and develop branch, both still have the issue. Thanks.

**Comment by devilx** [comment]
@rpietzsch sorry, the demo system doesn't run the dockerized Paperwork – even though this might probably be a good idea in future. I've created an issue relating to your problem: #215.

**Comment by nebulade** [comment]
I do see the missing stylesheets now being disabled in the views, but the page would still look like above in the screenshots. 

Is there anything obvious I miss about to build the full theme/stylesheet?

While looking at https://github.com/twostairs/paperwork/commit/a1b6a6a677787519a90bcb63295a1156ecd03495 it mentions some theme support, but I can only find https://github.com/twostairs/paperwork/issues/57 related to that. Does this mean we have to wait for Paperwork 3.0 to get better stylesheets?

**Comment by Liongold** [comment]
@nebulade Sorry but what do you mean? Are the stylesheets and JS files being loaded?

**Comment by stephen-hill** [comment]
I used the demo this morning and it was working perfectly.

**Comment by nebulade** [comment]
@Liongold I am sorry never mind, seemed to be functional, however the app was not fully working, yet. I was tracing the wrong issue ;-)

**Comment by nebulade** [comment]
To clarify for other readers, I simply hit #281
