### ISSUE TITLE
Deleting a notebook using the docker image causes page to freeze

### ISSUE THREAD

**Issue by absolutejam** [twostairs/paperwork#702]
I've fired up the docker image(s) via. docker-compose and got up and running.

When I attempt to delete a notebook (Both the default 'Welcome' and one I have created), the page just hangs until I refresh it.

Are there any logs that it would be worth me sending across?

Regards,
James.

**Comment by Liongold** [comment]
The browser's developer tools console and network tabs should help. Also, please specify which branch you're running.

**Comment by absolutejam** [comment]
Can't see anything happening in there. I'm running the master branch as of about a week ago.

I can create new notebooks and notes just fine, and even delete notes but it just freezes when I delete a notebook the page freezes.

Just going to destroy and spin up again and see what happens.

**Comment by absolutejam** [comment]
Same again after tearing it down my current containers and using `docker-compose up` again. I'm using 'db' as the database address - this should be fine, right?

**Comment by Liongold** [comment]
If you get the notes, then it should be good.

**Comment by Liongold** [comment]
Can you show a screenshot of the browser's network tab. The request should give at least an error code.

**Comment by vsviridov** [comment]
The modal dialog appears, but it is invisible. If you manually remove the "fade" class - it appears.

**Comment by Liongold** [comment]
Can anyone retry to confirm this bug? It should now be fixed.

**Comment by JamborJan** [comment]
Hey @Liongold in which branch have you fixed this? I'm going to rebuild my paperwork package and can test this.

Reference: https://github.com/JamborJan/paperwork/issues/47

**Comment by JamborJan** [comment]
I just tested with the latest master branch and the issue is still present.

**Comment by Liongold** [comment]
@JamborJan Sorry for the late reply. The pull request was merged to develop. It should be fixed on that branch. If you think master should be updated, feel free to open a pull request.

**Comment by JamborJan** [comment]
Hey @Liongold it's working like expected. One question: would it be possible to mentione the name of the notebook which will be deleted? This would ensure that nobody accedently deletes the wrong notebook.

**Comment by Liongold** [comment]
@JamborJan If it isn't a problem for you, can you open a new issue for your suggestion please. Until some of the pull request get merged, work can't go very far.

**Comment by Liongold** [comment]
Also, since @JamborJan has confirmed that it's fixed, this issue will be closed. Thanks for your feedback. If you encounter any issues, please open a new issue.
