### ISSUE TITLE
still unfinished subnotes

### ISSUE THREAD

**Issue by jacek-1210** [twostairs/paperwork#731]
I wrote about this a while ago. Now is this:

![paper_1](https://cloud.githubusercontent.com/assets/13505686/21444434/9dcb3062-c8ad-11e6-8c0c-1fe20da364c0.png)

After 1 click is this:

![paper_2](https://cloud.githubusercontent.com/assets/13505686/21444435/9dcc3c3c-c8ad-11e6-8bb7-c384a0f28a39.png)

should be like this:

![paper_3](https://cloud.githubusercontent.com/assets/13505686/21444501/4f8a277c-c8ae-11e6-89e2-b87e54c6ba58.png)

:(

**Comment by jacek-1210** [comment]
I don't understand. Children notebook ? How to ?

**Comment by Liongold** [comment]
Sorry for the confusion. Child notebooks is not an official term or any feature. In the pull request shown, child notebooks means notebooks that are in a collection (hence have a non-null parent_id - that's where child came from). Once merged, these notebooks will be better distinguished than now and should hopefully fix your issue. Once merged, you will only need to update the source files and run `gulp`. No database work is required for this. I hope I've explained better.

**Comment by jacek-1210** [comment]
I still don't understand about child notebooks: I created collection eg. "zdrowie" and next time created notebooks "badania" & "choroby" & "leczenie". Next I merge this notebooks into collection "zdrowie".  This are "child notebooks" (like the screenshots above) ? If not, how to correctly create child notebooks ? 
Sorry, my english is not very well.

**Comment by Liongold** [comment]
Yes those are the child notebooks.

**Comment by jacek-1210** [comment]
OK, so, some time ago I wrote about it, and now wanted only to recall: 

If I touch collection button, child notebooks should develop and distinguish from ordinary notebooks
After second touch collection button, child notebooks should collapse and hide

it still does not work that way. Problems with framework ?

**Comment by Liongold** [comment]
There's a pull request that should make that work. It's #736 and is still pending. When it's merged, this should work as you described.

**Comment by Liongold** [comment]
The pull request has now been merged. Can you re-test it please?

**Comment by jacek-1210** [comment]
Wow, nice. thx. Missing only: "After second touch (this same) collection button, child notebooks should collapse and hide". (Now, hide/collapse child notebooks, works only by touch another collection button)

**Comment by Liongold** [comment]
Fixed in #762.

**Comment by jacek-1210** [comment]
Hmm ?? Isn't fixed. After update, still, second touch/click this same collection button don't work (child notebooks don't hide)

**Comment by Liongold** [comment]
You need to wait until the pull request is merged before receiving the new feature.

**Comment by jacek-1210** [comment]
Some problems ?

And next problem: now isn't possible to move/remove notebook into/from collection. As I remember, in earlier versions it was possible. And isn't possible erase collection. :(
Now I have 2 identical collections % can't erase it :(

![paperwork1](https://cloud.githubusercontent.com/assets/13505686/25757696/d9df264e-31cb-11e7-95f4-d78313585e59.jpg)

**Comment by jacek-1210** [comment]
OK, I found in SQL & manual erased it

**Comment by Liongold** [comment]
What is the code shown in the Paperwork Settings page in the About tab please?

**Comment by jacek-1210** [comment]
Uppsss.   "0"      
What about this ?

**Comment by Liongold** [comment]
Do you have a fork installed? Did you touch the .git folder? Could you reinstall while keeping your database backed up and then re-attaching it to Paperwork.

**Comment by jacek-1210** [comment]
Sorry, last I broke the update. Now I get: 5d0287b7c72e14dcaa84d18cdf714d9551564b4f

**Comment by Liongold** [comment]
Please run `git pull` and then `npm install`, `bower install` and `gulp` again. You seem to be running an outdated version.

**Comment by Liongold** [comment]
@jacek-1210 Can this issue be closed?
