### ISSUE TITLE
Cloudron and Website Demos are not working

### ISSUE THREAD

**Issue by xkpd3** [twostairs/paperwork#834]
Hello,

The demo on the website is not working. Navigating to http://demo.paperwork.rocks results in a DNS error. The demo on cloudron is also not working, as there is no paperwork app installed nor in the app catalog.

Best Regards,
Stefan

**Comment by gramakri** [comment]
@xkpd3 (Co-founder of Cloudron.io here) Thanks for reporting, there seems to be some problem in our app store listing that has made some apps not appear. We are working on a fix.

**Comment by gramakri** [comment]
@xkpd3 Fixed now. You can try it at https://my-demo.cloudron.me (username/password: cloudron)

This issue can be closed.

**Comment by xkpd3** [comment]
@gramakri Works like a charm now. Thank you.

The issue is partially fixed. I keep it open as the domain demo.paperwork.rocks does not resolve.

**Comment by jsEveryDay** [comment]
Yupp, still no A records

> Lookup failed: demo.paperwork.rocks No data
> Whois query for demo.paperwork.rocks...
> Results returned from whois.unitedtld.com:
> Malformed request.

**Comment by Liongold** [comment]
I'll close this issue since the issue with Cloudron has been fixed (thanks @gramakri). The demo site has been suspended. There are no news on when it will be reactivated. Anyway, there's an issue for that #726. 

Thank you for your interest in Paperwork.
